from keyboard_utils.keyboard_special_key_map import special
keys = {
    ' ': [special['space']],
    'a': [0x04],
    'b': [0x05],
    'c': [0x06],
    'd': [0x07],
    'e': [0x08],
    'f': [0x09],
    'g': [0x0a],
    'h': [0x0b],
    'i': [0x0c],
    'j': [0x0d],
    'k': [0x0e],
    'l': [0x0f],
    'm': [0x10],
    'n': [0x11],
    'o': [0x12],
    'p': [0x13],
    'q': [0x14],
    'r': [0x15],
    's': [0x16],
    't': [0x17],
    'u': [0x18],
    'v': [0x19],
    'w': [0x1a],
    'x': [0x1b],
    'y': [0x1c],
    'z': [0x1d],
    'A': [special['lshift'], 0x04],
    'B': [special['lshift'], 0x05],
    'C': [special['lshift'], 0x06],
    'D': [special['lshift'], 0x07],
    'E': [special['lshift'], 0x08],
    'F': [special['lshift'], 0x09],
    'G': [special['lshift'], 0x0a],
    'H': [special['lshift'], 0x0b],
    'I': [special['lshift'], 0x0c],
    'J': [special['lshift'], 0x0d],
    'K': [special['lshift'], 0x0e],
    'L': [special['lshift'], 0x0f],
    'M': [special['lshift'], 0x10],
    'N': [special['lshift'], 0x11],
    'O': [special['lshift'], 0x12],
    'P': [special['lshift'], 0x13],
    'Q': [special['lshift'], 0x14],
    'R': [special['lshift'], 0x15],
    'S': [special['lshift'], 0x16],
    'T': [special['lshift'], 0x17],
    'U': [special['lshift'], 0x18],
    'V': [special['lshift'], 0x19],
    'W': [special['lshift'], 0x1a],
    'X': [special['lshift'], 0x1b],
    'Y': [special['lshift'], 0x1c],
    'Z': [special['lshift'], 0x1d],
    '1': [0x1e], 
    '2': [0x1f],
    '3': [0x20],
    '4': [0x21],
    '5': [0x22],
    '6': [0x23],
    '7': [0x24],
    '8': [0x25],
    '9': [0x26],
    '0': [0x27],
    '-': [0x2D],
    '=': [0x2E],
    '[': [0x2F],
    ']': [0x30],
    ';': [0x33],
    '`': [0x35],
    ',': [0x36],
    '.': [0x37],
    '/': [0x38],
    '!': [special['lshift'], 0x1e],
    '@': [special['lshift'], 0x1f],
    '#': [special['lshift'], 0x20],
    '$': [special['lshift'], 0x21],
    '%': [special['lshift'], 0x22],
    '^': [special['lshift'], 0x23],
    '&': [special['lshift'], 0x24],
    '*': [special['lshift'], 0x25],
    '(': [special['lshift'], 0x26],
    ')': [special['lshift'], 0x27],
    '_': [special['lshift'], 0x2D],
    '+': [special['lshift'], 0x2E],
    '{': [special['lshift'], 0x2F],
    '}': [special['lshift'], 0x30],
    '|': [special['lshift'], 0x31],
    ':': [special['lshift'], 0x33],
    '"': [special['lshift'], 0x34],
    '~': [special['lshift'], 0x35],
    '<': [special['lshift'], 0x36],
    '>': [special['lshift'], 0x37],
    '?': [special['lshift'], 0x38]
}

#Escaped Characters:
keys['\\'] = [0x31] #|
keys['\''] = [0x34] #"

def get_code(user_input):
    input_as_string = str(user_input)
    code = []
    for char in input_as_string:
        if char in keys.keys():
            code.append(keys[char])
    return code